[project]
name = "calc"
version = "0.1.0"
description = "Simple Reverse Polish Notation Calculator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.10.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

